# Streamlit secrets file for environment variables
# Add your OpenAI API key here for production
OPENAI_API_KEY = "your_openai_api_key_here"

# Optional: Add other API keys or configuration
# JOB_API_KEY = "your_job_api_key_here" 